name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install ⚙️
        run: npm install

      - name: Lint 💅
        run: npm run lint

      - name: Check types ✔️
        run: npm run check-ts
